### PR TITLE
Add xarray to environment requirements.txt

### PR DESCRIPTION
**Pull request by twsearle**
Add the `xarray` package to the list of requirements. Satisfies a requirement in `profile.py`.

### CODE REVIEW

**Comment by andrewgryan** [comment]
@twsearle I think the failing tests can be patched by converting to datetimes. The many flavours of datetime objects are becoming real maintenance issue that would be better tackled in a different PR. Quick and dirty fix for now should do it

**Comment by andrewgryan** [comment]
@twsearle it turns out that xarray is already in the conda environment at `0.7.0`. Perhaps this PR can be a tidy up of those two failing tests?

**Comment by twsearle** [comment]
I had a go at this and I think I have traced it to a difference in behaviour of numpy.ma.argmax. I have test case where it appears to be returning an index of zero in error (this is under the mask)? Perhaps I need a sanity check on this though.

We went from `numpy  1.17.5  py38h95a1406_0`   to `numpy   1.18.1   py38h95a1406_0`

Under  1.17.5  you get what you expect:
```
>>> import numpy as np
>>> import datetime as dt
>>> mask = [ True,  True, False,  True,  True]
>>> times = [dt.datetime(2019, 1, 1, 3, 0), dt.datetime(2019, 1, 1, 3, 15), dt.datetime(2019, 1, 1, 3, 30), dt.datetime(2019, 1, 1, 3, 45), dt.datetime(2019, 1, 1, 4, 0),]
>>> times = np.asarray(times, dtype='datetime64[s]')
>>> valid_times = np.ma.array(times, mask=mask)
>>> np.ma.argmax(valid_times)
2
>>> valid_times
masked_array(data=[--, --, datetime.datetime(2019, 1, 1, 3, 30), --, --],
             mask=[ True,  True, False,  True,  True],
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[s]')
```
Under 1.18.1 I get:
```
$python
>>> import numpy as np
>>> import datetime as dt
>>> mask = [ True,  True, False,  True,  True]
>>> times = [dt.datetime(2019, 1, 1, 3, 0), dt.datetime(2019, 1, 1, 3, 15), dt.datetime(2019, 1, 1, 3, 30), dt.datetime(2019, 1, 1, 3, 45), dt.datetime(2019, 1, 1, 4, 0),]
>>> times = np.asarray(times, dtype='datetime64[s]')
>>> valid_times = np.ma.array(times, mask=mask)
>>> np.ma.argmax(valid_times)
0
>>> valid_times
masked_array(data=[--, --, datetime.datetime(2019, 1, 1, 3, 30), --, --],
             mask=[ True,  True, False,  True,  True],
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[s]')
```

**Comment by andrewgryan** [comment]
@twsearle perhaps there is a different default `fill_value` for `datetime64` in numpy 1.18 than 1.17?

**Comment by twsearle** [comment]
I don't think so, they are both 'NaT' I think?

I think the problem is deeper:

```
>>> np.argmax(valid_times.filled())
0
```

**Comment by twsearle** [comment]
In both cases:
```
>>> valid_times.filled() 
array([                'NaT',                 'NaT',
       '2019-01-01T03:30:00',                 'NaT',
                       'NaT'], dtype='datetime64[s]')
>>> type(valid_times.filled()[0])
<class 'numpy.datetime64'>
```

**Comment by twsearle** [comment]
so confused!
```
>>> np.datetime64('NaT') > valid_times.filled()[2]
```

**Comment by andrewgryan** [comment]
Yarp https://numpy.org/devdocs/release/1.18.0-notes.html#numpy-argmin-argmax-min-max-returns-nat-if-it-exists-in-array

**Comment by andrewgryan** [comment]
https://github.com/numpy/numpy/pull/14717

**Comment by andrewgryan** [comment]
@twsearle I keep forgetting github references everything everywhere

**Comment by twsearle** [comment]
What? That is on purpose!? OK

**Comment by andrewgryan** [comment]
How about we stick with 1.17 for now?

**Comment by twsearle** [comment]
OK fair enough. I will change the requirements to <=0.17 for numpy. Probably worth learning how that works anyway!

**Comment by andrewgryan** [comment]
Agreed, I think there must be a good reason for the 1.18 version of `np.ma.argmax` that we ought to be using

**Comment by twsearle** [comment]
I think what we are supposed to do to fix this properly is use something like `np.nanargmax(dates.filled())`, but perhaps another day.

**Pull request merged**
