### PR TITLE
Initial gridded forecast support.

### PR DESCRIPTION
**Pull request by rhattersley**
Uses iris to provide access to [time x lat x lon] and [lat x lon] data from a variety of file formats.

Behold... some lovely looking data from a FieldsFile...
image

### CODE REVIEW

**Comment by rhattersley** [comment]
Still just at "sneak-preview" status - still needs tests for the new `ImageLoader`and `Navigator` classes. :wink:

**Comment by andrewgryan** [comment]
Thanks @rhattersley, well done! I like the unit testing and guard clauses around non-mappable cubes. You're right this is a good starting point and opens the door for further simplification using the `Group` concept we discussed yesterday.

**Comment by andrewgryan** [comment]
@rhattersley Just read your cube constraint, have you tried using this with a variable that has a pressure coordinate?

**Comment by rhattersley** [comment]
> have you tried using this with a variable that has a pressure coordinate

This PR won't accept data with a pressure coordinate. It's `tyx` or `yx` only at the moment.

**Comment by andrewgryan** [comment]
I think `tyx` and `yx` are good enough for now, let me know when you've added a few tests and I'll merge this back in. Adding `tzyx`, with `z` meaning something to a particular variable would be a nice `good for beginner` problem

**Comment by rhattersley** [comment]
Now with tests for the two new classes and all tests OK locally. Should be ready to merge once Travis gives it the :+1:

**Comment by andrewgryan** [comment]
Nice work!

**Pull request merged**
