### PR TITLE
Add an optional profile figure

### PR DESCRIPTION
**Pull request by twsearle**
Currently I am just duplicating the time series in profile.py, but you get the idea.

### CODE REVIEW

**Comment by twsearle** [comment]
@andrewgryan I have had another crack at this and I think it is pretty close. I think the two remaining issues (possibly for a different pull request?) are:
 * files which use this `dim0` dimension coordinate approach are untested and probably won't work
 * the `ProfileLoader` runs for every file in forest for this variable, rather than just the current time.

I don't think either of these are hard to fix, but I was hoping you could take a look at the changes and see what you think?

**Comment by andrewgryan** [comment]
@twsearle I'll take a look and see if I can offer some advice

**Comment by twsearle** [comment]
@andrewgryan I was procrastinating this morning and I tried to finish this one up. I think I have covered the two problems above, however it is a little tricky to test properly. I have been using the cache of Africa data you showed me:
```
$more multi-config.yaml 

files:
   - label: Africa
     pattern: "cache/*.nc"
     locator: file_system
     file_type: unified_model
$forest --show --config-file multi-config.yaml
```
But the output is not correct, even when I use the master branch. For whatever reason, it takes a long time to load and then doesn't display the surface colour mesh. However, things seem to work ok when I run `$forest --show cache/*.nc`.

I can't think of any more obvious improvements at this stage so I am removing the WIP tag.

**Comment by andrewgryan** [comment]
@twsearle we're now transitioning to https://forest.metoffice.cloud which will have a more formal production-ready release cycle. Our auto-deploy forest.informaticslab.co.uk will be retired in favour of having a dev version and a prod version. If you feel the changes in this PR lay good foundations for follow on work I can review it and merge it today. Banking progress as often as possible is what we should be doing

**Comment by twsearle** [comment]
Great thanks! Hopefully I haven't broken anything :)

**Comment by andrewgryan** [comment]
@twsearle if it is broken we can easily fix it or unwind the changes :wink:

**Comment by andrewgryan** [comment]
@twsearle spoke too soon. xarray isn't available in the old FOREST container

```
File "profile.py", line 48, in <module>:
import xarray Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/repo/forest/forest/main.py", line 8, in <module>
    from forest import (
  File "/repo/forest/forest/profile.py", line 48, in <module>
    import xarray
ModuleNotFoundError: No module named 'xarray'

```

**Comment by andrewgryan** [comment]
I'll submit a quick `try/except` PR to temporarily patch the issue. It might be a good time to retire `forest.informaticslab.co.uk` with a re-direct to `dev.forest.metoffice.cloud.dev.dev.dev`

**Pull request merged**
