### PR TITLE
Change saf to use xarray and handle NaNs 

### PR DESCRIPTION
**Pull request by eardkdw**
# Change saf to use xarray and handle NaNs

Switching to use xarray instead of netcdf4 module. Also handle NaNs in coordinates better (e.g. from whole-of-Africa satellite scan)

## Check list

Handy reminders of things to do ahead of merge

- [ ] Bump version number to reflect change, edit `forest/__init__.py`
  <sub>(Use semantic version x.y.z where x is major, y is feature, z is patch)</sub>

### CODE REVIEW

**Comment by andrewgryan** [comment]
@eardkdw nice work. Not sure `forest/saf.py` exists anymore, I moved it to `forest/drivers/saf.py` and did some refactoring on it.

**Comment by eardkdw** [comment]
I merged the file move in before I started the xarray/NaN stuff - I'm not sure why it's back.

**Comment by eardkdw** [comment]
It works without it - pushing the change.

**Comment by andrewgryan** [comment]
@eardkdw to optimize the search for a file I've made an assumption that the frequency of the files are 15-minutely. Is that the case, or should I relax that condition?

**Comment by eardkdw** [comment]
I think they are; I will have to check with Alex.

**Comment by eardkdw** [comment]
Alex says the current lot are, but some of the other satellites have a higher temporal resolution.

**Comment by andrewgryan** [comment]
OK, I'll make it frequency agnostic for now and when it becomes a problem we can optimize it for higher frequency files

**Comment by claretandy** [comment]
The current state of the art is 5-minute frequency from GOES-16 (geostationary over the US). I think Himawari is 10 minute, but in the Met Office we only download every 20

**Pull request merged**
