### PR TITLE
enable travis-ci

### PR DESCRIPTION
**Pull request by bjlittle**
This PR enables `travis-ci`, and sprinkles some absolute imports to allow pytest to work.

Note that, there are 3 failing tests and 16 skipped... I'll leave it to @andrewgryan to figure that out.

Also, you can test `forest` with `pytest` or `python setup.py test` now :wink:

### CODE REVIEW

**Comment by bjlittle** [comment]
closes #111

**Comment by bjlittle** [comment]
Once the tests move into the `test` directory from the `forest` directory, simply:

- update the `setup.cfg` file, changing `testpaths = forest` to `testpaths = test`, and
- update the `setup.py` file, changing, `test_suite = NAME` to `test_suite = "test"`

**Comment by andrewgryan** [comment]
@bjlittle I'll have a look at why those tests are failing, perhaps they are slightly out of date with the desired behaviour or are stale tests. It is worth pointing out that the **server/run-ec2.sh** should be upgraded to enable the correct PYTHONPATH inside the Docker container running FOREST on EC2, see 62c94f283e9acaf408f67211eb0ef9dbc36d5d6c

**Comment by andrewgryan** [comment]
Bokeh's machinery adds the **main.py** directory to the PYTHONPATH automatically which is why absolute imports were not used previously, but you're right this is the approach I've taken in my [simple_cli](/informatics-lab/forest/tree/simple_cli) branch, which is turning out to be anything but simple

**Comment by bjlittle** [comment]
@andrewgryan I'm in the office on Thursday/Friday, did you want me to swing by for a natter about this so that I can understand better?

**Comment by andrewgryan** [comment]
@bjlittle not essential I can fix/merge this one, but yeah if you'd like to drop by that would be good. There's plenty more to be done and I'd like to get people up and running ahead of the hackathon

**Comment by bjlittle** [comment]
@andrewgryan Cool. Unfortunately, I can't make the hackathon :cry: ... so this is my contribution, as such.

**Comment by bjlittle** [comment]
@andrewgryan ... don't know the connective tissue, but kinda begs the question of why the bokeh machinery requires to use PYTHONPATH... really?

**Comment by andrewgryan** [comment]
@bjlittle actually, it's really because the Docker container running on EC2 doesn't have forest installed as a package

**Comment by andrewgryan** [comment]
@bjlittle  could you skip the failing tests for now, e.g. `pytest.mark.skip('awaiting development')`, and add the `PYTHONPATH` change needed to pick up absolute path imports of forest? I think the added test infrastructure is a sufficient improvement for this PR

**Comment by andrewgryan** [comment]
Or `@unittest.skip('awaiting development')`, forgot we are using old fashioned `unittest` module

**Comment by bjlittle** [comment]
> actually, it's really because the Docker container running on EC2 doesn't have forest installed as a package

@andrewgryan More questions... so why isn't the Docker image installing `forest` from `conda-forge`? Or the dependencies of `forest` and it's development git branch?

**Comment by andrewgryan** [comment]
This is what we should be doing, could I borrow you some time tomorrow to get the Docker image and conda-forge recipes up-to-date/built on change to master?

**Comment by bjlittle** [comment]
@andrewgryan Skipping the tests done the job :tada:

**Comment by bjlittle** [comment]
@andrewgryan We're trying to hammer out the `iris` 2.3.0 release at the moment... spinning too many plates.

How's about I catch up with you next week? :wink:

**Comment by andrewgryan** [comment]
Next week is fine, I'll merge this PR back to trunk and patch up any deployment issues (if any) on master. I'm expecting a PYTHONPATH issue, but I can deal with that. Thanks for your help getting the pytest infrastructure up and running, I look forward to reviewing the other PRs soon

**Comment by andrewgryan** [comment]
I've merged master into my latest feature branch so look forward to tests running inside `test/` from now on, see f015efd72f2b653cc48aad5eeb3ca8089136510a

**Pull request merged**
