### PR TITLE
Components docs

### PR DESCRIPTION
**Pull request by andrewgryan**
A work in progress to make `Component` design pattern more transparent to new developers

### CODE REVIEW

**Comment by andrewgryan** [comment]
@twsearle this should encapsulate everything we struggled with today so that other people don't have to...

**Comment by andrewgryan** [comment]
https://forest-informaticslab.readthedocs.io/en/components-docs/howto.html#build-a-component

**Comment by andrewgryan** [comment]
@twsearle maybe the text should change to `add_subscriber` to reflect #260?

**Comment by twsearle** [comment]
Yes I think changing the text to `add_subscriber` would be a good call. 

I think this bit of documentation is quite helpful, thanks! I am already making use of it right now.  

One source of confusion for me is the term "reducer". My understanding is that, in our case, this is a function that reduces some input to a set of state changes, rather than changing the state directly? I guess I am not sure how much functional programming concepts should be assumed on the part of the developer. Perhaps we could put a reducer example from forest  in brackets, or a line explaining what they are?

**Comment by andrewgryan** [comment]
@twsearle how about a how-to guide for reducers? Seems like a concept people adding functionality might need to be aware of

**Pull request merged**
