### PR TITLE
Moved time-series stuff into separate module

### PR DESCRIPTION
**Pull request by caughtshort**
Prep work for adding vertical profiles

### CODE REVIEW

**Comment by andrewgryan** [comment]
@caughtshort I think there might be some git config settings needed to make your commits link to your GitHub account. The Contributor Licence Agreement assistant is not happy although we can probably ignore it, if you've signed as caughtshort

E.g. user name and email address
- `git config --global user.name caughtshort` 
- `git config --global user.email ...@metoffice.gov.uk`

Links to GitHub docs
- https://help.github.com/en/github/using-git/setting-your-username-in-git
- https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address#setting-your-commit-email-address-in-git

**Comment by andrewgryan** [comment]
Also the test suite can't find the extracted code.

Screenshot from 2019-10-29 11-33-15
Screenshot from 2019-10-29 11-33-48

**Comment by andrewgryan** [comment]
@caughtshort are there any planned updates for this PR? I would like to get it in as I think @stevehadd would like to add series support for CMIP6 #208

**Comment by rhattersley** [comment]
The lack of a signed CLA is the main sticking point here. Does anyone have another way to get in contact with @caughtshort?

**Comment by andrewgryan** [comment]
@rhattersley he's in my team so I'll poke him about this next time I see him

**Pull request closed without merging**
