### PR TITLE
Only update the time series when it is visible

### PR DESCRIPTION
**Pull request by twsearle**
This commit has some issues. Forest seems to behave strangely when initially opening with the tutorial data. The time series will disappear on the first click on the map and require two toggles of "time_series_visible" to reappear. I think this is to do with how I have managed the defaults. Also, I named a module "position" and immediately regretted it. Can you think of a better name that is less likely to be used as a variable?

### CODE REVIEW

**Comment by andrewgryan** [comment]
@twsearle I think to set the initial state correctly you want to do something like ``store.dispatch(series.set_on())`` in ``main.py``, e.g. instead of needing to use ``on_toggle()`` multiple times have an action that turns it on by default at the start. That way ``{..., 'time_series_visible': True, ...}`` would be in the initial state. Make sense?

**Comment by andrewgryan** [comment]
@twsearle instead of `position.py` how about `screen.py`, e.g. `screen.TapListener` and `screen.MarkDraw`?

Naming things is difficult, I reckon that module is short enough to be easy to understand. Future readers/authors can cook up a better name through usage

**Comment by andrewgryan** [comment]
@twsearle this is looking good, let me know if anything else is confusing

**Comment by twsearle** [comment]
> series.set_on()
I didn't do this, but I think I have got to the same place. Things seem a little better now and I am not seeing the same issue I was seeing before.

I have renamed position to screen. I think that makes a bit more sense and is less likely to give a naming clash! Thanks for the idea.

I am out of time today to work on this, but we can revisit it on Friday or you can commit it if you think its ready. I am a little nervous to take away the WIP, because I haven't tested it against a large number of files. I would like to know if I have made any difference to performance, or if I ought to improve my implementation somehow.

Thanks for the help

**Comment by andrewgryan** [comment]
@twsearle I'll give it another look, but as far as I can tell it's a sensible change. If you want me to hold off until Friday that's OK with me. Thanks for putting the effort in, very much appreciated

**Comment by andrewgryan** [comment]
@twsearle I'm happy with this change, it also provides a nice platform for building vertical profile functionality. Mainly since the x/y tap-event and marker placing are now decoupled from the time series. I reckon we could add profiles in on Friday without too much hassle

**Comment by twsearle** [comment]
@andrewgryan  If your happy to commit it, then great, I will remove the WIP thingy.

**Pull request merged**
