### PR TITLE
Saf variable names

### PR DESCRIPTION
**Pull request by eardkdw**
Displays `netCDF4.Variable` `long_name` instead of the key.

### CODE REVIEW

**Comment by andrewgryan** [comment]
@eardkdw it looks like #205 has resulted in a minor conflict, I can attempt to resolve it if you like?

**Comment by andrewgryan** [comment]
@eardkdw I like the idea of a `State` hash function

**Comment by andrewgryan** [comment]
@eardkdw this looks good, I'll merge it as soon as the CI checks pass

**Comment by eardkdw** [comment]
Let's me use lru_cache on the (now very expensive) saf.image function.
Still gets called four times, mind. Better than eleven, though.

**Comment by andrewgryan** [comment]
Are you finished working on it? Is it ready to merge?

**Comment by eardkdw** [comment]
It should be mergeable now, yes.

**Pull request merged**
