### PR TITLE
Automatic app termination on exit of browserwindow. 

### PR DESCRIPTION
**Pull request by wolfiex**
# Changes
 - Termination on browser window closing provides a clean exit and relinquishes control of the port (note: There is a couple of seconds delay as everything is shut down, and the message is printed to terminal). 
 - Conversion of git_cheat_sheet to a markdown file for easy reading. 

# App termination on exit of browserwindow. 

## Check list

- [x] Bump version number to reflect change, edit `forest/__init__.py`
  <sub>(Use semantic version x.y.z where x is major, y is feature, z is patch)</sub>

### CODE REVIEW

**Comment by andrewgryan** [comment]
@wolfiex thanks for the contribution! But I'm not really sure we want to terminate the app on browser window close. We have a long running app instance at https://forest.metoffice.cloud that we'd like to keep alive even when a user closes the tab.

**Comment by andrewgryan** [comment]
@wolfiex this could be a useful addition for a desktop app, which I guess was your intended use case

**Comment by andrewgryan** [comment]
@wolfiex I've thought about it some more, perhaps we want a `--keep-alive` flag if the intended purpose is to run a server. Or indeed have separate commands `forest-serve` for long running processes and `forest` for quick file viewing

**Comment by wolfiex** [comment]
> @wolfiex this could be a useful addition for a desktop app, which I guess was your intended use case

@andrewgryan Yes it was - as I could not find a way to cleanly exit and free up the port when using it as a desktop app. 

My suggestion would be to use an environmental variable available on the MO computer as a switch - where if **it exists**, forest will **not exit**, e.g. :

`METOFFICE=true forest ... `

or 
```
export METOFFICE=true;
forest ...
```
and have within `server_lifecycle.py` the following instead:

```python 
def on_session_destroyed(session_context):
    '''
    Function called when a session is closed 
    (e.g. tab closed or time out)
    '''
    import sys,os
  
    # ** insert here **
    if (not  os.getenv('METOFFICE')):

         sys.exit('\033[1;31mThe session has ended - tab closed or timeout. \n\n --- Terminating the Forest progam and relinquishing control of port. ---\033[1;00m')

```

I assume the MO instance will be likely automated, run once and left whereas the desktop version may be run many times by different people at any one point.

**Comment by andrewgryan** [comment]
@wolfiex sorry for not getting back to this sooner. I've thought about it and think this might be a good justification for implementing sub-commands, e.g. like git commit etc.

To take a quick look at a file and kill the process when you're done looking at it, maybe something like this?
```
# Auto-shutdown server on tab close
forest view file.nc
```
Then to run a server version, i.e. share with colleagues or demo at a meeting.
```
# Keep server alive on tab close
forest serve file.nc
```
I've asked people in my time to submit their ideas too. Do you like this approach?

**Comment by andrewgryan** [comment]
@wolfiex this nicely separates the commands to allow **forest view** to be an electron app and for **forest serve** to be a stateless server one day

**Comment by andrewgryan** [comment]
@wolfiex I've played with this and here's how to implement the behavior

1. Add `--auto-shutdown` to the list of forest specific commands in `forest.cli.main`, `action='set_true'` I think is the option to use
2. Add `AUTO_SHUTDOWN = False` to `forest.data`, this is where server globals live
3. Add `data.AUTO_SHUTDOWN = args.auto_shutdown` in `forest.main` after parse_args()
4. Use `if data.AUTO_SHUTDOWN: ...` in `server_lifecycle.py`
5. Profit

The sub-command design is syntactic sugar and can be added in a later PR

**Comment by andrewgryan** [comment]
@wolfiex this looks good to me, I'll merge it in now

**Pull request merged**
