### PR TITLE
Forest 72 slider

### PR DESCRIPTION
**Pull request by andrewgryan**
This branch is finally ready for review, the difficulty was finding a way to react gracefully to changes in RGBA array shapes and to communicate those changes to the client-side CustomJS callbacks. This has been achieved by extracting the caching into a class (`forest.image.CachedRGBA`) and hooking up the CustomJS.args when the array shapes change

The other minor annoyance was getting the initial state of the app to turn off the HoverTool associated with the slider. Unfortunately in Bokeh there is no way to set the active state of a Tool from the server side and there are no `bokeh.events` that are triggered on page load. My solution was to set `active_inspect` tools to `None` on figure construction

This branch improves on the existing unit test suite, add npm test for the JS client side code and adds Sphinx docs to build documentation for an eventual forest library targetting the Scientist community who will inevitably want to write their own scripts using Forest-like features

The `image.py` module adds a Slider and Toggle class to make the single figure layout more usable. I have adjusted `forest.control` to have a better layout to work with the responsive design features of bokeh

### CODE REVIEW

**Comment by stevehadd** [comment]
Some initial comments while I'm working through the review: 

- README.md - when running the unittest python command, I get an error unless I update my 

- PYTHONPATH. Maybe include something about this. If I update my PYTHONPATH, I then get an error in the javascript test, which I don't know how to fix, so some instructions on this may be needed as well.
 - doc/ Sphinx generated documentation looks good!
 - bokeh_apps/*/main.py  - maybe we should select which of three ways of calling main we want.  I think the one in  the satellite/simim app seems most pythonic, maybe put that in the 2 model app?
- tests/* More tests, hooray!
 - tests/bokeh_apps/  - what are these apps for, and how do I run them?
 - forest_lib/forest/image.py  - the comments mention handlinfg GlyphRenderer and ColumnDataSource objects. How are CDSs used to display images in the Slider or Toggle tool? I don't see any code that seems to do that.

**Comment by andrewgryan** [comment]
The Slider and Toggle tools are independent of the application glue code. It is the responsibility of `main.py` or `ForestController` to hook things up to each other. I'll improve the docs to illustrate that idea

**Comment by andrewgryan** [comment]
Hi Stephen,

I've addressed you reviewer comments by improving the documentation and rationalising how the two model app is initialised. Let me know if there's anything else I need to address or if you need help merging?

Cheers,

Andy

**Comment by stevehadd** [comment]
That all looks good to me now. I was interested to see that one can provide a html template for the bokeh page, as described [here](https://bokeh.pydata.org/en/latest/docs/user_guide/server.html) , I didn't know about that at all. I have learnt a lot doing this review! I'll do the merge tomorrow.

**Comment by stevehadd** [comment]
All done now, and seems to be working fine locally. 
Shall I update the forest.informaticslab.co.uk server to use the new revision, or leave it as just being on forestdev.informaticslab.co.uk.

Another thing to consider is that the new version no longer contain the interactive display, as thats not part of the new layout, and I thought it better not to try add it in during the merge but rather let you decide how it fit into the new design. The code is of course still there and can easily be added in how you see fit.

**Pull request merged**
